ENVIRONMENT: "development"

DATA_DIRECTORY: "./data/untracked_data"
INPUT_SHAPE: [32, 32, 3]

CATEGORIES_COUNT: 43
CATEGORIES_IDS_TO_NAMES_CSV_PATH: "./data/signs_ids_to_names.csv"

MODEL_WEIGHTS_PATH: "./data/untracked_data/traffic-signs-model.h5"

FLASK:

  DEBUG: True

TRAIN:

  batch_size: 128


